### PR TITLE
@fixed http2

### PR DESCRIPTION
**Pull request by MaximeMazet**

### CODE REVIEW

**Comment by RubenVerborgh** [comment]
The HTTP2 API is completely different.

**Comment by gpetrov** [comment]
http2 API is not completely different - it is fully backwards compatible.

Shame that this project is going to a dead end

**Comment by RubenVerborgh** [comment]
> http2 API is not completely different

Well, this PR broke all the tests: https://travis-ci.org/github/follow-redirects/follow-redirects/builds/694253804
That should be an indication.

You can also just check the actual API and see that it is completely different: https://nodejs.org/api/http2.html

> Shame that this project is going to a dead end

https://github.com/sponsors/RubenVerborgh

**Comment by gpetrov** [comment]
Have you inspected any of this failures @RubenVerborgh ? Most of them fail because the tests use too old node version ...
http2 is available from node 8.7 and up...

**Comment by RubenVerborgh** [comment]
> Have you inspected any of this failures @RubenVerborgh ?

Yes, have you? https://travis-ci.org/github/follow-redirects/follow-redirects/jobs/694253809

> Most of them fail because the tests use too old node version

No, they fail because this PR is literally one character spread across two commits, instead of the actual work needed for HTTP/2 compatibility.  I think we've wasted more than enough time here already, so I will lock this thread.

**Pull request closed without merging**
