### PR TITLE
Update test.js

### PR DESCRIPTION
**Pull request by Lydia02**
Use recent url parse

### CODE REVIEW

**Comment by pravi** [comment]
@RubenVerborgh actually this is required for express 5.0.0-beta.1 which uses mime 3.0 (url-parse was mentioned wrongly).

**Comment by RubenVerborgh** [comment]
@pravi follow-redirects does not use express.

**Comment by pravi** [comment]
@RubenVerborgh it needs express to run the tests https://github.com/follow-redirects/follow-redirects/blob/main/package.json#L54

**Comment by pravi** [comment]
I'm just giving more context to why we wanted this change in the first place, you can wait till express release 5.0 stable version or decide to stay with express 4 itself for tests. We already have this patch in debian but having it merged here will help us with maintenance in the long term.

**Comment by RubenVerborgh** [comment]
But why would I want Express 5 in the tests? The challenge of follow-redirects is to keep working from Node 4.x all the way to the latest version. Express 5 will not help us with that objective.

**Comment by pravi** [comment]
@RubenVerborgh that is fair enough. In Debian, we want to run tests with latest version of modules as we don't want to maintain multiple versions of express. Since you don't want to run tests with express 5, we will keep the patches in the package to make the tests run with express 5 (or rather mime 3.0). We usually prefer to avoid maintaining patches so we discuss with each upstream project. If the goals are not aligned we maintain patches.

**Comment by RubenVerborgh** [comment]
I'm interested in supporting your use case; but I'm not sure how a _test_ dependency of a package is relevant.
i.e., express is not part of the final build of the package, so it should never end up on any Debian system.
To be honest, we don't even need express in the test code; it's just how the original developer had set up the testing.

**Pull request closed without merging**
