### PR TITLE
possibly leak free handling of abort and timeout

### PR DESCRIPTION
**Pull request by splitice**
This requires further testing, and likely a rewrite but I wanted to share this in reference to https://github.com/axios/axios/issues/3457

### CODE REVIEW

**Comment by RubenVerborgh** [comment]
> This requires further testing

Could you confirm whether it helps for axios/axios#3457?

> likely a rewrite

Yes; I rebased on `main` so we can see test failures.

**Comment by splitice** [comment]
Initial testing is positive.

My issue test script was failing within 3 minutes before, now it has not failed after over an hour. 

I'm doing some longer runs currently. And I'm running this fork in a real world application that was leaking memory (what caused my investigation).

**Comment by RubenVerborgh** [comment]
Super, thanks!

**Comment by splitice** [comment]
Script ran for two hours before running out of memory. Substantial improvement. There however may still be other leaks in either follow-redirects or axios to find and fix.

However given the thousands or millions or requests performed over 2 hours I highly doubt it's leaking the full response object this time.

**Comment by splitice** [comment]
I wouldnt mind testing follow-redirects independantly of axios for further information.

If there is some script that someone wants to design for that purpose I'm willing to run it.

**Comment by RubenVerborgh** [comment]
Following up in https://github.com/follow-redirects/follow-redirects/pull/152

**Pull request closed without merging**
