### PR TITLE
Declare `debug` as optional using `peerDependenciesMeta`

### PR DESCRIPTION
**Pull request by ylemkimon**
Related: #135 and #140.

This will result in:
- no change in package managers that don't support `peerDependenciesMeta` **EDIT (Aug. 16):** without `peerDependencies` declaration
- no warning for undeclared peer dependency, especially in Yarn 2 with PnP

so it's completely backward compatible.

### CODE REVIEW

**Comment by ylemkimon** [comment]
@RubenVerborgh 
- npm doesn't support `peerDependenciesMeta` without `peerDependencies` yet, so no change in npm (https://git.io/JJdys)
- https://github.com/yarnpkg/berry/pull/531
- https://github.com/pnpm/pnpm/pull/2143

**Comment by RubenVerborgh** [comment]
What evidence do we have that this PR works?

**Comment by ylemkimon** [comment]
@RubenVerborgh I've setup a test repo at [ylemkimon/peer-deps-meta-test](https://github.com/ylemkimon/peer-deps-meta-test). [`master` branch](https://github.com/ylemkimon/peer-deps-meta-test/actions/runs/210940448) installs the current version v1.13.0 and [`patch` branch](https://github.com/ylemkimon/peer-deps-meta-test/actions/runs/210943028) installs this PR. Note the warning is printed in [`master` branch with Yarn 2](https://github.com/ylemkimon/peer-deps-meta-test/runs/990711051?check_suite_focus=true#step:9:34) but not printed in [`patch` branch with Yarn 2](https://github.com/ylemkimon/peer-deps-meta-test/runs/990717631?check_suite_focus=true#step:9:35).

**Comment by RubenVerborgh** [comment]
Excellent, thanks!

**Pull request merged**
