### PR TITLE
Add statusCode to `beforeRedirect` callback

### PR DESCRIPTION
**Pull request by SergeBabich**
A simple additional parameter that will help me a lot.

Thank you!

### CODE REVIEW

**Comment by RubenVerborgh** [comment]
Thanks; needs tests though.

**Comment by SergeBabich** [comment]
@RubenVerborgh do I need to fix tests?

**Comment by RubenVerborgh** [comment]
@SergeBabich No, but add them. There is nothing that validates you're actually returning the status code.

**Review by luizrenato2012 — APPROVED** [review]

**Comment by RubenVerborgh** [comment]
There are no tests; will reopen when there are.

**Pull request closed without merging**
